Repository Run-Us/Runimo-iOS, pull requests merged in 2024-11, with the labels that each got.

#51 [UI] 마이페이지 탭 화면
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Assets.xcassets/Image/Join/trash.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Join/trash.imageset/trash 1.png
  RunUs/RunUs/Assets.xcassets/Image/Join/trash.imageset/trash.png
  RunUs/RunUs/Assets.xcassets/Image/User/edit_profile.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/User/edit_profile.imageset/edit_profile 1.png
  RunUs/RunUs/Assets.xcassets/Image/User/edit_profile.imageset/edit_profile.png
  RunUs/RunUs/View/MyPage/MyGraph.swift
  RunUs/RunUs/View/MyPage/MyTab.swift
  RunUs/RunUs/View/MyPage/PostCard.swift
  RunUs/RunUs/View/MyPage/RecordCard.swift
  RunUs/RunUs/View/MyTab.swift
  RunUs/RunUs/View/Onboarding/JoinPage.swift
  RunUs/RunUs/ViewModel/MyPageViewModel.swift
Labels: 💄 UI

#53 [Refactor]의존성 주입 방식 변경
  RunUs/RunUs/RunUsApp.swift
  RunUs/RunUs/Utils/MapPage.swift
  RunUs/RunUs/View/GroupRun/CreateGroupRunPage.swift
  RunUs/RunUs/View/GroupRun/StartGroupRunPage.swift
  RunUs/RunUs/View/Run/FinishRunningPage.swift
  RunUs/RunUs/View/Run/RunTab.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
  RunUs/RunUs/View/Run/RunningPage.swift
  RunUs/RunUs/View/Run/RunningPostPage.swift
  RunUs/RunUs/View/Run/RunningProgressPage.swift
Labels: ♻️ Refactor

#54 [FIX & REFACTOR] 혼자 달리기 러닝 중 페이지 스와이프가 3번까지 되는 문제 해결
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/RunUsApp.swift
  RunUs/RunUs/View/GroupRun/CreateGroupRunPage.swift
  RunUs/RunUs/View/GroupRun/StartGroupRunPage.swift
  RunUs/RunUs/View/Run/RunTab.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
  RunUs/RunUs/View/Run/RunningPage.swift
  RunUs/RunUs/View/Run/RunningProgressPage.swift
  RunUs/RunUs/ViewModel/RunningViewModel.swift
Labels: 🐛 Bug, ♻️ Refactor

#52 [Feat] 참가자 리스트 화면
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Assets.xcassets/Image/Character/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Character/character_default.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Character/character_default.imageset/character_2.png
  RunUs/RunUs/Assets.xcassets/Image/Character/character_default.imageset/character_3.png
  RunUs/RunUs/Assets.xcassets/Image/Character/character_default.imageset/character_default.png
  RunUs/RunUs/Model/AggregateParticipants.swift
  RunUs/RunUs/Model/ParticipantInfo.swift
  RunUs/RunUs/Model/PollingManager.swift
  RunUs/RunUs/Service/ParticipationService.swift
  RunUs/RunUs/Service/WebSocketService.swift
  RunUs/RunUs/Utils/Participant.swift
  RunUs/RunUs/View/GroupRun/CreateGroupRunPage.swift
  RunUs/RunUs/View/GroupRun/JoinGroupRunPage.swift
  RunUs/RunUs/View/GroupRun/Participants/ParticipantList.swift
  RunUs/RunUs/View/GroupRun/Participants/ParticipantProfile.swift
  RunUs/RunUs/View/GroupRun/Participants/RunningParticipant.swift
  RunUs/RunUs/View/GroupRun/Participants/RunningParticipants.swift
  RunUs/RunUs/View/GroupRun/StartGroupRunPage.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
Labels: ✨ Feat, 💄 UI

#58 [FEAT] 마이페이지 디자인 수정 적용 및 날짜 관리
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Assets.xcassets/Image/MyPage/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/MyPage/arrow_down.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/MyPage/arrow_down.imageset/chevron-down 1.png
  RunUs/RunUs/Assets.xcassets/Image/MyPage/arrow_down.imageset/chevron-down.png
  RunUs/RunUs/Model/RunningInfo.swift
  RunUs/RunUs/Model/UserToken.swift
  RunUs/RunUs/Service/MyPageService.swift
  RunUs/RunUs/View/MyPage/DateSheet.swift
  RunUs/RunUs/View/MyPage/MyGraph.swift
  RunUs/RunUs/View/MyPage/MyTab.swift
  RunUs/RunUs/View/MyPage/PostCard.swift
  RunUs/RunUs/View/MyPage/PostCardList.swift
  RunUs/RunUs/View/MyPage/RecordCard.swift
  RunUs/RunUs/View/Run/FinishRunningPage.swift
  RunUs/RunUs/View/Run/RunningPostPage.swift
  RunUs/RunUs/ViewModel/DateManager.swift
  RunUs/RunUs/ViewModel/MyPageViewModel.swift
Labels: ✨ Feat, 💄 UI

#59 그룹런 생성하기 화면 에서 발생하는 이슈 해결 및 필요한 팝업 뷰 추가
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Model/AggregateParticipants.swift
  RunUs/RunUs/Model/RunningSessionInfo.swift
  RunUs/RunUs/Service/ParticipationService.swift
  RunUs/RunUs/Service/RunningSessionService.swift
  RunUs/RunUs/Utils/PasscodeGenerator.swift
  RunUs/RunUs/View/GroupRun/CreateGroupRunPage.swift
  RunUs/RunUs/View/GroupRun/JoinGroupRunPage.swift
  RunUs/RunUs/View/GroupRun/StartGroupRunPage.swift
  RunUs/RunUs/ViewModel/PollingManager.swift
  RunUs/RunUs/ViewModel/RunningViewModel.swift
Labels: 🐛 Bug, 💄 UI
