Repository Run-Us/Runimo-iOS, pull requests merged in 2024-10, with the labels that each got.

#23 [FIX] 러닝 데이터 수집
  RunUs/RunUs/Model/RunningInfo.swift
  RunUs/RunUs/Service/WebSocketService.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
  RunUs/RunUs/View/Run/RunningProgressPage.swift
  RunUs/RunUs/ViewModel/MapViewModel.swift
  RunUs/RunUs/ViewModel/MotionManager.swift
Labels: bug

#25 [Refactor] 직관적인 이름으로 네이밍 수정
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Model/ParticipantInfo.swift
  RunUs/RunUs/Model/RunningSessionInfo.swift
  RunUs/RunUs/Service/ParticipationService.swift
  RunUs/RunUs/Service/RunningSessionService.swift
  RunUs/RunUs/Service/WebSocketService.swift
  RunUs/RunUs/View/CharacterTab.swift
  RunUs/RunUs/View/CrewTab.swift
  RunUs/RunUs/View/GroupRun/CreateGroupRunPage.swift
  RunUs/RunUs/View/GroupRun/GroupRunMapPage.swift
  RunUs/RunUs/View/GroupRun/GroupRunPage.swift
  RunUs/RunUs/View/GroupRun/JoinGroupRunPage.swift
  RunUs/RunUs/View/GroupRun/Participants/ParticipantList.swift
  RunUs/RunUs/View/GroupRun/Participants/ParticipantProfile.swift
  RunUs/RunUs/View/GroupRun/Participants/RunningParticipant.swift
  RunUs/RunUs/View/GroupRun/StartGroupRunPage.swift
  RunUs/RunUs/View/HomeTab.swift
  RunUs/RunUs/View/MyTab.swift
  RunUs/RunUs/View/Onboarding/LoginPage.swift
  RunUs/RunUs/View/Run/RunAlonePage.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
  RunUs/RunUs/View/Run/RunningPage.swift
  RunUs/RunUs/View/Run/RunningProgressPage.swift
  RunUs/RunUs/View/TabBar.swift
  RunUs/RunUs/ViewModel/MapViewModel.swift
Labels: enhancement

#30 [FIX] stomp로 보내는 메세지의 인코딩 문제 해결
  RunUs/RunUs/Model/RunningInfo.swift
  RunUs/RunUs/Service/WebSocketService.swift
  RunUs/RunUs/View/GroupRun/StartGroupRunPage.swift
  RunUs/RunUs/View/Run/RunningProgressPage.swift
Labels: bug, ✨ Feat

#31 [FIX] 성공적으로 웹소켓 메세지를 받을 수 있도록 수정
  RunUs/RunUs/Model/RunningInfo.swift
  RunUs/RunUs/Service/WebSocketService.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
Labels: bug

#39 [FEAT] 로그인 화면 및 회원가입 화면 개발
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Assets.xcassets/Image/Login/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Login/apple_login_button.imageset/AppleLoginButton.png
  RunUs/RunUs/Assets.xcassets/Image/Login/apple_login_button.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Login/apple_login_button.imageset/apple_login_button_2x.png
  RunUs/RunUs/Assets.xcassets/Image/Login/apple_login_button.imageset/apple_login_button_3x.png
  RunUs/RunUs/Assets.xcassets/Image/Login/kakao_login_button.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Login/kakao_login_button.imageset/kakao_login_button.png
  RunUs/RunUs/Assets.xcassets/Image/Login/kakao_login_button.imageset/kakao_login_button_2x.png
  RunUs/RunUs/Assets.xcassets/Image/Login/kakao_login_button.imageset/kakao_login_button_3x.png
  RunUs/RunUs/Assets.xcassets/Image/Login/login_view_1.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Login/login_view_1.imageset/LoginView_1.png
  RunUs/RunUs/Assets.xcassets/Image/Login/login_view_2.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Login/login_view_2.imageset/login_view_2.png
  RunUs/RunUs/Assets.xcassets/Image/Login/login_view_3.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Login/login_view_3.imageset/login_view_3.png
  RunUs/RunUs/Assets.xcassets/Image/User/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/User/default_user_profile.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/User/default_user_profile.imageset/UserProfile_1x.png
  RunUs/RunUs/Assets.xcassets/Image/User/default_user_profile.imageset/UserProfile_2x.png
  RunUs/RunUs/Assets.xcassets/Image/User/default_user_profile.imageset/UserProfile_3x.png
  RunUs/RunUs/Assets.xcassets/Image/User/plus_profile_button.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/User/plus_profile_button.imageset/plus_profile_button_2x.png
  RunUs/RunUs/Assets.xcassets/Image/User/plus_profile_button.imageset/plus_profile_button_3x.png
  RunUs/RunUs/Assets.xcassets/Image/User/plus_profile_button.imageset/plus_profile_button_x1.png
  RunUs/RunUs/Assets.xcassets/Image/app_logo.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/app_logo.imageset/SplashLogo.svg
  RunUs/RunUs/Assets.xcassets/Image/kakao_login_button.imageset/kakao_login_large_wide.png
  RunUs/RunUs/Assets.xcassets/Join/Contents.json
  RunUs/RunUs/Assets.xcassets/Join/imageIcon.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Join/imageIcon.imageset/imageIcon_1x.png
  RunUs/RunUs/Assets.xcassets/Join/imageIcon.imageset/imageIcon_2x.png
  RunUs/RunUs/Assets.xcassets/Join/imageIcon.imageset/imageIcon_3x.png
  RunUs/RunUs/RunUsApp.swift
  RunUs/RunUs/View/Onboarding/AddProfileSheet.swift
  RunUs/RunUs/View/Onboarding/GenderPickerSheet.swift
  RunUs/RunUs/View/Onboarding/JoinPage.swift
  RunUs/RunUs/View/Onboarding/LoginPage.swift
Labels: 💄 UI

#40 [FEAT] 달리기 공통 페이지 제작
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Assets.xcassets/Image/NavigationBar/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Run/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Run/run_pause.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Run/run_pause.imageset/run_pause 1.png
  RunUs/RunUs/Assets.xcassets/Image/Run/run_pause.imageset/run_pause.png
  RunUs/RunUs/Assets.xcassets/Image/Run/run_start.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Run/run_start.imageset/run_start 1.png
  RunUs/RunUs/Assets.xcassets/Image/Run/run_start.imageset/run_start.png
  RunUs/RunUs/Assets.xcassets/Image/Run/run_stop.imageset/Contents.json
  RunUs/RunUs/Assets.xcassets/Image/Run/run_stop.imageset/run_stop 1.png
  RunUs/RunUs/Assets.xcassets/Image/Run/run_stop.imageset/run_stop.png
  RunUs/RunUs/Utils/MapPage.swift
  RunUs/RunUs/Utils/SegmentedPicker.swift
  RunUs/RunUs/View/GroupRun/CreateGroupRunPage.swift
  RunUs/RunUs/View/GroupRun/GroupRunMapPage.swift
  RunUs/RunUs/View/GroupRun/GroupRunPage.swift
  RunUs/RunUs/View/GroupRun/StartGroupRunPage.swift
  RunUs/RunUs/View/Run/RunAlonePage.swift
  RunUs/RunUs/View/Run/RunTab.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
  RunUs/RunUs/View/Run/RunningPage.swift
  RunUs/RunUs/View/Run/RunningProgressPage.swift
  RunUs/RunUs/View/TabBar.swift
Labels: ✨ Feat, 💄 UI

#47 [FEAT] 러닝 페이지 프로그래스 바 & page dots
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Assets.xcassets/Color/highlight.colorset/Contents.json
  RunUs/RunUs/Utils/MapPage.swift
  RunUs/RunUs/View/Run/ProgressBar.swift
  RunUs/RunUs/View/Run/RunTab.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
  RunUs/RunUs/View/Run/RunningPage.swift
  RunUs/RunUs/View/Run/RunningProgressPage.swift
  RunUs/RunUs/ViewModel/MapViewModel.swift
Labels: 💄 UI

#48 [UI] 러닝 활동 저장하기
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Extension/FontExtension.swift
  RunUs/RunUs/Model/RunningInfo.swift
  RunUs/RunUs/Utils/PopUp.swift
  RunUs/RunUs/View/Run/FinishRunningPage.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
  RunUs/RunUs/View/Run/RunningPage.swift
  RunUs/RunUs/View/Run/RunningPostPage.swift
  RunUs/RunUs/View/Run/ShareRunningRecordPage.swift
Labels: ✨ Feat, 💄 UI
