Repository Run-Us/Runimo-iOS, pull requests merged in 2024-09, with the labels that each got.

#5 [FEAT] 카카오 로그인 앱 세팅
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/RunUsApp.swift
  RunUs/RunUs/View/LoginPage.swift
  RunUs/RunUs/ViewModel/AuthViewModel.swift
Labels: ✨ feat

#7 [FEAT]: Home 화면 Tabbar 기능 개발
  RunUs/RunUs/View/CharacterPage.swift
  RunUs/RunUs/View/CrewPage.swift
  RunUs/RunUs/View/HomePage.swift
  RunUs/RunUs/View/MainPage.swift
  RunUs/RunUs/View/MyPage.swift
  RunUs/RunUs/View/RunningPage.swift
Labels: ✨ feat

#8 [FIX]: project.pbxproj 파일 추가 반영
  RunUs/RunUs.xcodeproj/project.pbxproj
Labels: bug

#13 [FEAT]: 그룹 생성하기 화면 개발
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Utils/MapPage.swift
  RunUs/RunUs/Utils/NoticeBar.swift
  RunUs/RunUs/View/GroupRun/CreateGroupRunPage.swift
  RunUs/RunUs/View/GroupRun/RunnerParticipant.swift
  RunUs/RunUs/View/GroupRun/StartGroupRunPage.swift
  RunUs/RunUs/View/MainPage.swift
  RunUs/RunUs/View/Onboarding/LoginPage.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
  RunUs/RunUs/View/Run/RunningPage.swift
  RunUs/RunUs/View/Run/RunningProgressPage.swift
  RunUs/RunUs/View/RunningPage.swift
Labels: ✨ feat

#17 [FEAT] 혼자 달리기 기능
  RunUs/RunUs/Utils/MapPage.swift
  RunUs/RunUs/View/Run/RunAlonePage.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
  RunUs/RunUs/View/Run/RunningProgressPage.swift
  RunUs/RunUs/ViewModel/MapViewModel.swift
Labels: ✨ Feat, 💄 UI

#19 [Refactor] run 탭 을 제외한 탭 뷰 코드 제거
  RunUs/RunUs/View/MainPage.swift
Labels: 💄 UI

#20 [FEAT] 러닝 진행 시 시간, 페이스, 거리 저장
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Model/RunningInfo.swift
  RunUs/RunUs/View/GroupRun/RunGroupPage.swift
  RunUs/RunUs/View/Run/RunAlonePage.swift
  RunUs/RunUs/View/Run/RunningMapPage.swift
  RunUs/RunUs/View/Run/RunningProgressPage.swift
  RunUs/RunUs/ViewModel/MapViewModel.swift
  RunUs/RunUs/ViewModel/MotionManager.swift
Labels: ✨ Feat

#21 [FEAT] 자동 로그인
  RunUs/RunUs.xcodeproj/project.pbxproj
  RunUs/RunUs/Service/AuthService.swift
  RunUs/RunUs/View/MainPage.swift
  RunUs/RunUs/View/MyPage.swift
  RunUs/RunUs/View/Onboarding/LoginPage.swift
  RunUs/RunUs/View/Run/RunningPage.swift
  RunUs/RunUs/ViewModel/AuthViewModel.swift
Labels: ✨ Feat
